# Generated by Django 5.2 on 2025-06-18 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensas',
            name='justificativo',
            field=models.FileField(default='arquivos', upload_to='justificativos/'),
        ),
        migrations.AlterField(
            model_name='faceencoding',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_encoding', to=settings.AUTH_USER_MODEL),
        ),
    ]
